### ISSUE TITLE
Directory structures

### ISSUE THREAD

**Issue by pamelarussell** [ti243/celloline#1]
Hi,

Could you please post a sample directory structure corresponding to config_example.txt? I've attempted to follow the instructions, but I'm running into a lot of issues with directory structures as I try to run the pipeline. In particular, I can't tell which variables are supposed to specify a directory and which specify a regular file.

Thanks!
Pam

**Comment by fobinf** [comment]
Dear Pam,

Thank you for your message. I have pasted below most of the tree of our amazon instance. For many purposes I think that the amazon instance is a good place to start with the pipe line to get to know it.  I have attached the corresponding config 

projects
└── example
    ├── config.txt
    └── raw
        ├── SingleTestCell#1_1.fq
        ├── SingleTestCell#1_2.fq
        ├── SingleTestCell#2_1.fq
        ├── SingleTestCell#2_2.fq
        ├── SingleTestCell#3_1.fq
        └── SingleTestCell#3_2.fq
references
└── Mouse
    ├── chr9.fa
    ├── chr9.gtf
    ├── Mus_musculus_GRCm38_79_dna_primary_assembly_ERCC_phix_fa.fa
    ├── Mus_musculus_GRCm38_79_dna_primary_assembly_ERCC_phix_fa.fa.fai
    └── Mus_musculus_GRCm38_79_dna_primary_assembly_ERCC_phix_fa.gtf
temp
tools
├── mapper
│   ├── bowtie
│   │   ├── bowtie -> /usr/bin/bowtie
│   │   └── bowtie-build -> /usr/bin/bowtie-build
│   ├── bowtie2
│   │   ├── bowtie2 -> /usr/bin/bowtie2
│   │   ├── bowtie2-align -> /usr/bin/bowtie2-align
│   │   └── bowtie2-build -> /usr/bin/bowtie2-build
│   ├── bwa
│   │   └── bwa -> /usr/bin/bwa
│   ├── gmap
│   │   ├── gmap -> /usr/local/bin/gmap
│   │   ├── gmap_build -> /usr/local/bin/gmap_build
│   │   ├── gnapl -> /usr/local/bin/gsnapl
│   │   ├── gsnap -> /usr/local/bin/gsnap
│   │   ├── gtf_splicesites -> /usr/local/bin/gtf_splicesites
│   │   └── iit_store -> /usr/local/bin/iit_store
│   ├── salmon
│   │   └── salmon -> /usr/local/bin/salmon
│   ├── STAR
│   │   └── STAR -> /home/ubuntu/bin/STAR/bin/Linux_x86_64_static/STAR
│   └── tophat2
│       └── tophat2 -> /usr/bin/tophat2
└── quantification
    ├── cufflinks
    │   └── cufflinks -> /usr/bin/cufflinks
    └── HTSeq
        └── htseq-count -> /usr/local/bin/htseq-count

[config.txt](https://github.com/Teichlab/celloline/files/221880/config.txt)
